#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Contacts.Droid.Resource", IsApplication=true)]

namespace Contacts.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Contacts.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Contacts.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bullet_dark_icon_100x100 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bullet_light_icon_100x100 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Contacts = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Contacts_128x128 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int default_portrait = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gradient_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_76 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_small_40 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int info = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int location = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mainbackground = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int MainImage = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int minus = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int phone = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int plus = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
